import { StyleSheet } from 'react-native';

import { radius } from '@/styles/tokens';

export const homeStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#1B1D27',
  },
  topBar: {
    position: 'relative',
    paddingTop: 56,
    paddingHorizontal: 18,
    paddingBottom: 12,
    backgroundColor: '#7B3FF3',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    gap: 14,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoBubble: {
    width: 42,
    height: 42,
    borderRadius: radius.pill,
    backgroundColor: '#CBA8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 26,
    height: 26,
    resizeMode: 'contain',
  },
  brandTitle: {
    color: '#fff',
    fontSize: 36,
    fontWeight: '700',
    lineHeight: 40,
  },
  brandSubtitle: {
    color: '#F0E8FF',
    fontSize: 14,
  },
  searchWrap: {
    position: 'relative',
  },
  searchInput: {
    height: 42,
    borderRadius: radius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    color: '#fff',
    paddingLeft: 14,
    paddingRight: 70,
    fontSize: 16,
  },
  searchClearButton: {
    position: 'absolute',
    right: 38,
    top: 10,
    zIndex: 12,
  },
  searchLoader: {
    position: 'absolute',
    right: 12,
    top: 10,
  },
  searchResults: {
    marginTop: 8,
    borderRadius: radius.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#D9C5FF',
    backgroundColor: '#F7F1FF',
  },
  searchResultItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E7DCFA',
  },
  searchResultName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2B1858',
  },
  searchResultAddress: {
    marginTop: 2,
    fontSize: 12,
    color: '#5A4A7C',
  },
  selectedPlaceCard: {
    marginTop: 6,
    borderRadius: radius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.24)',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  selectedPlaceTextWrap: {
    flex: 1,
    gap: 2,
  },
  selectedPlaceName: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  selectedPlaceAddress: {
    color: '#F4E9FF',
    fontSize: 12,
  },
  selectedPlaceMeta: {
    color: '#E4D3FF',
    fontSize: 12,
    fontWeight: '600',
  },
  selectedPlaceActionStack: {
    justifyContent: 'center',
    gap: 8,
    width: 84,
  },
  selectedPlaceCancelButton: {
    width: '100%',
    height: 32,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(43, 26, 82, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(214, 195, 255, 0.75)',
  },
  selectedPlaceCancelButtonText: {
    color: '#EFE8FF',
    fontSize: 12,
    fontWeight: '700',
  },
  selectedPlaceButton: {
    width: '100%',
    height: 32,
    borderRadius: radius.pill,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  selectedPlaceButtonStop: {
    backgroundColor: '#D64545',
  },
  selectedPlaceButtonText: {
    color: '#2A1652',
    fontSize: 12,
    fontWeight: '700',
  },
  mapArea: {
    flex: 1,
    paddingTop: 10,
    position: 'relative',
  },
  mapContainer: {
    flex: 1,
    position: 'relative',
  },
  loader: {
    marginTop: 12,
  },
  chipRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  chip: {
    borderRadius: 18,
    minHeight: 40,
    paddingHorizontal: 8,
    paddingVertical: 6,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  greenChip: {
    backgroundColor: '#20B300',
  },
  redChip: {
    backgroundColor: '#FF472F',
  },
  blueChip: {
    backgroundColor: '#3A6FF2',
  },
  chipLabel: {
    color: '#fff',
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  routeSummary: {
    color: '#E6EAF5',
    textAlign: 'center',
    marginBottom: 8,
    fontSize: 13,
    fontWeight: '600',
  },
  navigateButton: {
    alignSelf: 'center',
    backgroundColor: '#7B3FF3',
    borderRadius: radius.pill,
    paddingHorizontal: 18,
    paddingVertical: 9,
    marginBottom: 6,
  },
  stopButton: {
    backgroundColor: '#D64545',
  },
  navigateButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  routeActionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  topLeftExitButton: {
    position: 'absolute',
    left: 14,
    top: 36,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D6C3FF',
    zIndex: 20,
  },
  floatingModeButton: {
    position: 'absolute',
    left: 14,
    bottom: 212,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#7B3FF3',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#BDA3FF',
    shadowColor: '#140D25',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
    zIndex: 30,
  },
  navCard: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -6,
    backgroundColor: 'rgba(17, 19, 29, 0.95)',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 98,
    borderWidth: 1,
    borderColor: 'rgba(168, 138, 242, 0.62)',
    gap: 4,
    zIndex: 40,
  },
  navCardTitle: {
    color: '#CDB7FF',
    fontSize: 12,
    fontWeight: '700',
  },
  navInstruction: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
  },
  navMeta: {
    color: '#D8DBE7',
    fontSize: 12,
  },
  error: {
    color: '#FF857A',
    textAlign: 'center',
    marginBottom: 8,
  },
});
