import { StyleSheet } from 'react-native';

import { palette, radius } from '@/styles/tokens';

export const settingsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#EDEDF0',
  },
  topBar: {
    paddingTop: 56,
    paddingHorizontal: 12,
    paddingBottom: 12,
    backgroundColor: '#7B3FF3',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 1,
  },
  logoBubble: {
    width: 46,
    height: 46,
    borderRadius: radius.pill,
    backgroundColor: '#CBA8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: 26,
    height: 26,
    resizeMode: 'contain',
  },
  titleStack: {
    gap: 2,
    flexShrink: 1,
  },
  brandTitle: {
    color: '#FFFFFF',
    fontSize: 38,
    fontWeight: '700',
    lineHeight: 40,
  },
  brandSubtitle: {
    color: '#F2E9FF',
    fontSize: 14,
    fontWeight: '500',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    backgroundColor: 'rgba(60, 23, 126, 0.42)',
    borderRadius: radius.pill,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  logoutText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  container: {
    paddingHorizontal: 10,
    paddingTop: 18,
    paddingBottom: 140,
    gap: 12,
  },
  pageTitle: {
    color: '#111017',
    fontWeight: '700',
    fontSize: 34,
    lineHeight: 38,
    marginBottom: 6,
    paddingHorizontal: 10,
  },
  card: {
    backgroundColor: '#D5D1E3',
    borderRadius: radius.lg,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  cardHeader: {
    borderBottomWidth: 1,
    borderBottomColor: '#BAB4CA',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 9,
  },
  cardTitle: {
    color: '#201D2B',
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '600',
  },
  cardRows: {
    backgroundColor: '#DAD6E5',
  },
  row: {
    paddingHorizontal: 8,
    paddingVertical: 9,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#BAB4CA',
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  iconWrap: {
    width: 18,
    alignItems: 'center',
  },
  rowLabel: {
    color: '#17141F',
    fontSize: 14,
    fontWeight: '500',
    flexShrink: 1,
  },
  error: {
    color: palette.danger,
    paddingHorizontal: 10,
  },
});
